//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    rules: {
      'import/no-cycle': 'off',
      'import/order': 'off',
      'sort-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/require-await': 'off',
      'pnpm/json-enforce-catalog': 'off',
    },
  },
  {
    // shadcn component sources. These are generated by the shadcn CLI and
    // replaced wholesale by `shadcn add`, so edits here do not survive — and
    // the two rules below want edits that would be wrong anyway.
    //
    // `no-unnecessary-condition` fires on guards the types call redundant but
    // the runtime does not: `api?.off()` where the embla instance may be gone
    // by cleanup, `inputOTPContext?.slots` where the context is undefined
    // outside its provider. Removing those guards trades a lint error for a
    // runtime crash.
    files: ['src/components/ui/**'],
    rules: {
      '@typescript-eslint/no-unnecessary-condition': 'off',
      'no-shadow': 'off',
    },
  },
  {
    ignores: ['eslint.config.js', 'prettier.config.js'],
  },
]
