/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiConsultancyRouteImport } from './routes/api.consultancy'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiCorporateRequestRouteImport } from './routes/api.corporate-request'
import { Route as ApiCustomProgrammeRouteImport } from './routes/api.custom-programme'
import { Route as ApiNewsletterRouteImport } from './routes/api.newsletter'
import { Route as CapacityBuildingIndexRouteImport } from './routes/capacity-building.index'
import { Route as CapacityBuildingBuilderRouteImport } from './routes/capacity-building.builder'
import { Route as CapacityBuildingCorporateRequestRouteImport } from './routes/capacity-building.corporate-request'
import { Route as CapacityBuildingCoursesRouteImport } from './routes/capacity-building.courses'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyCertificateIdRouteImport } from './routes/verify.$certificateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsultancyRoute = ApiConsultancyRouteImport.update({
  id: '/api/consultancy',
  path: '/api/consultancy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorporateRequestRoute = ApiCorporateRequestRouteImport.update({
  id: '/api/corporate-request',
  path: '/api/corporate-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomProgrammeRoute = ApiCustomProgrammeRouteImport.update({
  id: '/api/custom-programme',
  path: '/api/custom-programme',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterRoute = ApiNewsletterRouteImport.update({
  id: '/api/newsletter',
  path: '/api/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacityBuildingIndexRoute = CapacityBuildingIndexRouteImport.update({
  id: '/capacity-building/',
  path: '/capacity-building/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacityBuildingBuilderRoute = CapacityBuildingBuilderRouteImport.update({
  id: '/capacity-building/builder',
  path: '/capacity-building/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacityBuildingCorporateRequestRoute =
  CapacityBuildingCorporateRequestRouteImport.update({
    id: '/capacity-building/corporate-request',
    path: '/capacity-building/corporate-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const CapacityBuildingCoursesRoute = CapacityBuildingCoursesRouteImport.update({
  id: '/capacity-building/courses',
  path: '/capacity-building/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateIdRoute = VerifyCertificateIdRouteImport.update({
  id: '/verify/$certificateId',
  path: '/verify/$certificateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/consultancy': typeof ApiConsultancyRoute
  '/api/contact': typeof ApiContactRoute
  '/api/corporate-request': typeof ApiCorporateRequestRoute
  '/api/custom-programme': typeof ApiCustomProgrammeRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/capacity-building/builder': typeof CapacityBuildingBuilderRoute
  '/capacity-building/corporate-request': typeof CapacityBuildingCorporateRequestRoute
  '/capacity-building/courses': typeof CapacityBuildingCoursesRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/capacity-building/': typeof CapacityBuildingIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/consultancy': typeof ApiConsultancyRoute
  '/api/contact': typeof ApiContactRoute
  '/api/corporate-request': typeof ApiCorporateRequestRoute
  '/api/custom-programme': typeof ApiCustomProgrammeRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/capacity-building/builder': typeof CapacityBuildingBuilderRoute
  '/capacity-building/corporate-request': typeof CapacityBuildingCorporateRequestRoute
  '/capacity-building/courses': typeof CapacityBuildingCoursesRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/capacity-building': typeof CapacityBuildingIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/verify': typeof VerifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/consultancy': typeof ApiConsultancyRoute
  '/api/contact': typeof ApiContactRoute
  '/api/corporate-request': typeof ApiCorporateRequestRoute
  '/api/custom-programme': typeof ApiCustomProgrammeRoute
  '/api/newsletter': typeof ApiNewsletterRoute
  '/capacity-building/builder': typeof CapacityBuildingBuilderRoute
  '/capacity-building/corporate-request': typeof CapacityBuildingCorporateRequestRoute
  '/capacity-building/courses': typeof CapacityBuildingCoursesRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/capacity-building/': typeof CapacityBuildingIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/privacy'
    | '/terms'
    | '/api/consultancy'
    | '/api/contact'
    | '/api/corporate-request'
    | '/api/custom-programme'
    | '/api/newsletter'
    | '/capacity-building/builder'
    | '/capacity-building/corporate-request'
    | '/capacity-building/courses'
    | '/resources/$slug'
    | '/services/$slug'
    | '/verify/$certificateId'
    | '/capacity-building/'
    | '/resources/'
    | '/services/'
    | '/verify/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/privacy'
    | '/terms'
    | '/api/consultancy'
    | '/api/contact'
    | '/api/corporate-request'
    | '/api/custom-programme'
    | '/api/newsletter'
    | '/capacity-building/builder'
    | '/capacity-building/corporate-request'
    | '/capacity-building/courses'
    | '/resources/$slug'
    | '/services/$slug'
    | '/verify/$certificateId'
    | '/capacity-building'
    | '/resources'
    | '/services'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/privacy'
    | '/terms'
    | '/api/consultancy'
    | '/api/contact'
    | '/api/corporate-request'
    | '/api/custom-programme'
    | '/api/newsletter'
    | '/capacity-building/builder'
    | '/capacity-building/corporate-request'
    | '/capacity-building/courses'
    | '/resources/$slug'
    | '/services/$slug'
    | '/verify/$certificateId'
    | '/capacity-building/'
    | '/resources/'
    | '/services/'
    | '/verify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiConsultancyRoute: typeof ApiConsultancyRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiCorporateRequestRoute: typeof ApiCorporateRequestRoute
  ApiCustomProgrammeRoute: typeof ApiCustomProgrammeRoute
  ApiNewsletterRoute: typeof ApiNewsletterRoute
  CapacityBuildingBuilderRoute: typeof CapacityBuildingBuilderRoute
  CapacityBuildingCorporateRequestRoute: typeof CapacityBuildingCorporateRequestRoute
  CapacityBuildingCoursesRoute: typeof CapacityBuildingCoursesRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  VerifyCertificateIdRoute: typeof VerifyCertificateIdRoute
  CapacityBuildingIndexRoute: typeof CapacityBuildingIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consultancy': {
      id: '/api/consultancy'
      path: '/api/consultancy'
      fullPath: '/api/consultancy'
      preLoaderRoute: typeof ApiConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/corporate-request': {
      id: '/api/corporate-request'
      path: '/api/corporate-request'
      fullPath: '/api/corporate-request'
      preLoaderRoute: typeof ApiCorporateRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/custom-programme': {
      id: '/api/custom-programme'
      path: '/api/custom-programme'
      fullPath: '/api/custom-programme'
      preLoaderRoute: typeof ApiCustomProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter': {
      id: '/api/newsletter'
      path: '/api/newsletter'
      fullPath: '/api/newsletter'
      preLoaderRoute: typeof ApiNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity-building/': {
      id: '/capacity-building/'
      path: '/capacity-building'
      fullPath: '/capacity-building/'
      preLoaderRoute: typeof CapacityBuildingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity-building/builder': {
      id: '/capacity-building/builder'
      path: '/capacity-building/builder'
      fullPath: '/capacity-building/builder'
      preLoaderRoute: typeof CapacityBuildingBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity-building/corporate-request': {
      id: '/capacity-building/corporate-request'
      path: '/capacity-building/corporate-request'
      fullPath: '/capacity-building/corporate-request'
      preLoaderRoute: typeof CapacityBuildingCorporateRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity-building/courses': {
      id: '/capacity-building/courses'
      path: '/capacity-building/courses'
      fullPath: '/capacity-building/courses'
      preLoaderRoute: typeof CapacityBuildingCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certificateId': {
      id: '/verify/$certificateId'
      path: '/verify/$certificateId'
      fullPath: '/verify/$certificateId'
      preLoaderRoute: typeof VerifyCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiConsultancyRoute: ApiConsultancyRoute,
  ApiContactRoute: ApiContactRoute,
  ApiCorporateRequestRoute: ApiCorporateRequestRoute,
  ApiCustomProgrammeRoute: ApiCustomProgrammeRoute,
  ApiNewsletterRoute: ApiNewsletterRoute,
  CapacityBuildingBuilderRoute: CapacityBuildingBuilderRoute,
  CapacityBuildingCorporateRequestRoute: CapacityBuildingCorporateRequestRoute,
  CapacityBuildingCoursesRoute: CapacityBuildingCoursesRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  VerifyCertificateIdRoute: VerifyCertificateIdRoute,
  CapacityBuildingIndexRoute: CapacityBuildingIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
